server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PG_SERVER}:5432/product
    username: admin
    password: admin123
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database: POSTGRESQL
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none

  application:
    name: product

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
