apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    creation_method: github
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: yogeshdsg/learning:kube-product-example-image
          imagePullPolicy: Always
          env:
            - name: PG_SERVER
              value: "postgres-service"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 5
          ports:
            - name: http
              containerPort: 8080   # Should match the Port that the container listens on
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: product
